eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8769
spring:
  application:
    name: service-zuul
  sleuth:
    web:
      client:
        enabled: true # 设置开启请求跟踪
    sampler:
        probability: 1.0
  zipkin:
    base-url: http://localhost:9090/  # 配置zipkinserver地址.

## 路由配置 routes api-a:path 访问路径 serviceId:对应服务名称。
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

