server:
  port: 8762

spring:
  application:
    name: service-hi
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
info:
    app.name : server-hi
    company.name : www.ly.com
    build.artifactId : $project.artifactId$
    build.version : $project.version$


